version: "3"
services:
  nginx:
    image: nginx:latest
    networks:
      - network
    volumes:
      - /home/woohaen88/nginx.conf:/etc/nginx/nginx.conf
      - static-volume:/data/static
      - media-volume:/data/media
    ports:
      - 80:80

  django_container_gunicorn:
    image: django_test_image:3
    networks:
      - network
    volumes:
      - static-volume:/home/all-about-camping/static
      - media-volume:/home/all-about-camping/media


networks:
  network:

volumes:
  static-volume:
  media-volume: